.gitignore, pom.xml
Hi @johngrimes,
I needed to upgrade the HAPI version from 4.0.0 to 4.0.3 to avoid a dependency on a 4.0.0-SNAPSHOT pom which is not available in Maven Central.
The HAPI 4.0.3 release notes confirm the issue: https://hapifhir.io/hapi-fhir/docs/introduction/changelog.html#hapi-fhir-403-igloo-point-release
Cheers.
=> Upgrade HAPI minor version to avoid build issues

fhir-server/src/main/java/au/csiro/pathling/QueryHelpers.java, fhir-server/src/main/java/au/csiro/pathling/fhirpath/NonLiteralPath.java, fhir-server/src/main/java/au/csiro/pathling/fhirpath/function/WhereFunction.java, fhir-server/src/main/java/au/csiro/pathling/fhirpath/operator/BooleanOperator.java, fhir-server/src/main/java/au/csiro/pathling/fhirpath/operator/ComparisonOperator.java, fhir-server/src/main/java/au/csiro/pathling/fhirpath/operator/MathOperator.java, fhir-server/src/main/java/au/csiro/pathling/fhirpath/operator/MembershipOperator.java, fhir-server/src/main/java/au/csiro/pathling/fhirpath/parser/InvocationVisitor.java, fhir-server/src/test/java/au/csiro/pathling/fhirpath/parser/ParserTest.java, fhir-server/src/test/resources/responses/ParserTest/testAggregationFollowingNestedWhere.csv
Omission of `$this` now resolves correctly to the current element, and `$this` is passed through to nested function invocations. The outer resource can be accessed through `%resource` or `%context`.
Joining within function arguments uses the element ID from the $this context to handle multiple rows per resource.
Fixes #202.
=> Improve handling of $this within arguments

fhir-server/src/main/java/au/csiro/pathling/update/ImportExecutor.java
=> Making import executor resilient to malformed request with missing "name"

fhir-server/src/main/java/au/csiro/pathling/fhirpath/function/CountFunction.java, fhir-server/src/test/java/au/csiro/pathling/test/TestDataImporter.java, fhir-server/src/test/java/au/csiro/pathling/test/builders/DatasetBuilder.java
This change fixes an issue where the result of the `count` function would be incorrect when used on the result of the `resolve` or `reverseResolve` function.
An example of an expression which is affected by this is:
```
Patient.reverseResolve(Condition.subject)
.subject
.resolve()
.ofType(Patient)
.count()
```
The result should be equal to the number of Condition resources associated to the Patient resource through the `subject` element.
=> Fix incorrect counting of resources when references are in use

lib/import/package-lock.json, lib/import/package.json, lib/js/package-lock.json, lib/js/package.json
This allows users to trace right back to the original source code, using the source maps that are already bundled.
=> Include TypeScript sources in NPM libraries

fhir-server/src/main/java/au/csiro/pathling/config/StorageConfiguration.java, fhir-server/src/main/java/au/csiro/pathling/spark/Spark.java, fhir-server/src/main/resources/application.yml
This change does away with the S3 variables in the Pathling configuration, in favor of allowing the user to set the Hadoop AWS configuration directly.
This allows for advanced configurations such as setting credentials via environment variables and via the EC2 metadata service. By default the configuration now supports a chain of authentication providers that should work for most use cases.
=> Allow greater control over S3 configuration

lib/python/pathling/context.py
Within the library, logging happens through Spark and is governed by the configuration that gets fed to Spark. This is not always under our control.
There doesn't seem to be an easy way to configure Pathling logging independently of Spark logging - at least not one that would work well in all deployment contexts.
Resolves #1180.
=> Remove logging_level parameter and improve documentation

.trivyignore, encoders/pom.xml, encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/R4DataTypeMappings.scala, fhir-server/pom.xml, lib/import/pom.xml, lib/js/pom.xml, lib/python/Dockerfile, lib/python/pom.xml, library-api/pom.xml, pom.xml, site/pom.xml, terminology/pom.xml, utilities/pom.xml
Resolves #1220.
Tested on Databricks runtimes 11.3, 12.0 and 12.1.
=> Switching to Cast() constructor common between spark-catalyst 3.3 and 3.4

lib/python/MANIFEST.in, lib/python/pathling/etc.py, lib/python/pom.xml, lib/python/setup.py, library-api/pom.xml, library-runtime/.gitignore, library-runtime/pom.xml, pom.xml, utilities/pom.xml, utilities/src/main/java/au/csiro/pathling/utilities/ObjectHolder.java
=> Create library runtime jar 

lib/python/pathling/context.py, library-api/src/main/java/au/csiro/pathling/library/PathlingContext.java, pom.xml, utilities/src/main/java/au/csiro/pathling/PathlingVersion.java
=> Fix problems with resolution of git.properties by giving it a unique name

lib/R/pom.xml
Fixing R build to always run 'doxygen2' and generate the 'NAMESPACE' file required for package installation.
Previously it was only generated with 'docs' profile enabled.
=> Fixing R build to always generate the 'NAMESPACE' file.

encoders/src/main/scala/au/csiro/pathling/encoders/Expressions.scala, encoders/src/main/scala/au/csiro/pathling/encoders/SerializerBuilder.scala, encoders/src/test/java/au/csiro/pathling/encoders/FhirEncodersTest.java
Changing the SPARK encoding of empty non-primitive elements in HAPI objects to produce NULL values rather than empty structs/arrays.
For example the encoding of:
```
"identifier" : [
{
"use" : "official",
"system" : "https://github.com/synthetichealth/synthea",
"value" : "d2120f2d-bc32-096d-d854-1a1e73a05f0d"
}
],
```
produce the row:
```
Row(identifier=[Row(id=None, use='official', type=None, system='
[https://github.com/synthetichealth/synthea'](https://github.com/synthetichealth/synthea%27)
, value='e4fc9c8b-66b7-7f4b-a033-39acfc7633fa', period=None, assigner=None)])
```
where composite elements such aas period or assigner as set to NULL (None).
The same also applies to empty elements with `many` cardinality. They produce NULL rather then an empty `array()`.
=> Changing the SPARK encoding of empty non-primitive elements in HAPI objects

.github/workflows/test.yml, fhir-server/pom.xml, fhir-server/src/test/java/au/csiro/pathling/jmh/SpringBootJmhContext.java, fhir-server/src/test/java/au/csiro/pathling/test/benchmark/AggregateBenchmark.java, fhir-server/src/test/java/au/csiro/pathling/test/benchmark/PathlingBenchmarkRunner.java
Moving benchmark execution to a forked VM (from the maven one) and adding the explicit cleanup of the application context(s) created for the spring autowired benchmarks.
This should provide better isolation of the benchmark run from the maven build process.
=> Moving benchmark execution to a forked VM and adding spring context cleanup

encoders/src/main/scala/au/csiro/pathling/encoders/Catalyst.scala, encoders/src/main/scala/au/csiro/pathling/encoders/EncoderUtils.scala, encoders/src/main/scala/au/csiro/pathling/encoders/QuantitySupport.scala, encoders/src/main/scala/au/csiro/pathling/encoders/SerializerBuilder.scala, encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/DataTypeMappings.scala, encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/DecimalCustomCoder.scala, encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/IdCustomCoder.scala, encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/R4DataTypeMappings.scala, encoders/src/main/scala/au/csiro/pathling/sql/types/FlexiDecimalSupport.scala, library-runtime/pom.xml
Implementing changes necessary run on Databrick RT 14.3 LTS (with Spark 3.5.0).
- Relocating hibernate-validatation to avoid conflict with the older version in the runtime.
- Introducing Catalyst compatibility layer to address incompatible changes in InvokeStatic constructor introduced post 3.5.x  and deployed in Databrick runtime.
=> Implementing changes necessary run on Databricks with Spark 3.5.0 (RT 14.3 LTS)

encoders/src/main/scala/au/csiro/pathling/encoders/SchemaProcessor.scala, encoders/src/main/scala/au/csiro/pathling/encoders/SerializerBuilder.scala, encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/R4DataTypeMappings.scala, encoders/src/test/java/au/csiro/pathling/encoders/FhirEncodersTest.java, encoders/src/test/java/au/csiro/pathling/encoders/LightweightFhirEncodersTest.java, encoders/src/test/java/au/csiro/pathling/encoders/SchemaConverterTest.java, encoders/src/test/java/au/csiro/pathling/encoders/TestData.java, fhir-server/src/test/java/au/csiro/pathling/fhirpath/parser/ParserTest.java, fhirpath/src/main/java/au/csiro/pathling/fhirpath/element/ReferencePath.java, fhirpath/src/test/java/au/csiro/pathling/fhirpath/parser/FhirPathTest.java, fhirpath/src/test/java/au/csiro/pathling/fhirpath/parser/FhirpathTest.java
=> Implementing full encoding and decoding support for References

fhirpath/src/test/resources/fhirpath-js/config.yaml
Non of the operators is currently supported including '+' which will be added in the future.
Resolves #2155.
=> Raise exception for any arithmetic operator on String. 

encoders/pom.xml, examples/java/PathlingJavaApp/.gitignore, examples/java/PathlingJavaApp/README.md, examples/java/PathlingJavaApp/pom.xml, examples/java/PathlingJavaApp/src/main/java/au/csiro/pathling/examples/PathlingJavaApp.java, examples/java/PathlingJavaApp/src/main/resources/log4j2.properties, examples/scala/PathlingScalaApp/.gitignore, examples/scala/PathlingScalaApp/README.md, examples/scala/PathlingScalaApp/build.sbt, examples/scala/PathlingScalaApp/project/build.properties, examples/scala/PathlingScalaApp/project/plugins.sbt, examples/scala/PathlingScalaApp/src/main/resources/log4j2.properties, examples/scala/PathlingScalaApp/src/main/scala/au/csiro/pathling/examples/PathlingScalaApp.scala, fhirpath/pom.xml, fhirpath/src/main/java/au/csiro/pathling/views/Column.java, fhirpath/src/main/java/au/csiro/pathling/views/FhirView.java, fhirpath/src/test/java/au/csiro/pathling/views/FhirViewValidationTest.java, library-api/pom.xml, library-runtime/pom.xml, pom.xml, terminology/pom.xml, utilities/pom.xml
- Adding new Scala and Java example projects
- Fixed Column constructor in FhirView.column() method to use Column.single() builder instead of deprecated constructor
- Updated test to use proper Column builder pattern
- Downgraded Jackson version from 2.16.1 to 2.15.4 for compatibility
- Modified the build to pass sources and docs from `library-api` and `fhirpath` modules into the library runtime
Resolves #2456.
=> Add example Java and Scala projects

lib/python/pathling/bulk.py, lib/python/pathling/datasource.py, lib/python/pathling/spark.py, lib/python/requirements/dev.txt, lib/python/tests/conftest.py, lib/python/tests/mockserver.py, lib/python/tests/test_bulk.py, lib/python/tests/test_datasource.py, lib/python/tests/test_spark.py
Resolves #2376.
Also make improvements to the bulk() datasource API, including support for temporary directory as the output_dir.
=> Add WireMock tests to bulk client functionality

fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java, fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/SystemDslTest.java
This PR improves the error message when users attempt to select a FHIR choice element without using `ofType()`. 
Previously, users would receive a cryptic error message:
> "Must have a fhirType or a definition"
Now they receive a more helpful message:
> "Selection of mixed collection not supported: [elementName]"
This provides clearer guidance about the need to use `ofType()` when working with choice elements in FHIR resources.
- Enhanced error handling in `Collection.java` to detect choice element selection scenarios
- Added specific error message for choice element selection attempts
- Added test case to verify the improved error message
A new test case has been added to `SystemDslTest.java` to verify that the improved error message is shown when attempting to select a choice type …
=> Fix unclear error message for choice element selection

lib/R/R/dependencies.R, lib/python/pathling/context.py
=> Remove hadoop-aws from default Spark config in Python and R libraries
