- encoders/core/pom.xml
- encoders/pom.xml
- encoders/r4/pom.xml
- fhir-server/pom.xml
- fhir-server/src/main/java/au/csiro/pathling/FhirServerContainer.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/AnalyticsServer.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/AnalyticsServerCapabilities.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/AnalyticsServerConfiguration.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/AuthorisationInterceptor.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/SmartConfigurationInterceptor.java
- fhir-server/src/main/resources/fhir/aggregate.OperationDefinition.json
- fhir-server/src/main/resources/fhir/import.OperationDefinition.json
- fhir-server/src/main/resources/fhir/search.OperationDefinition.json
- pom.xml
- site/docs/deployment.md
- site/pom.xml
> CapabilityStatement should advertise security capabilities

- encoders/core/pom.xml
- encoders/pom.xml
- encoders/r4/pom.xml
- fhir-server/pom.xml
- fhir-server/src/main/java/au/csiro/pathling/fhir/AuthorisationInterceptor.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/ErrorReportingInterceptor.java
- fhir-server/src/main/resources/fhir/aggregate.OperationDefinition.json
- fhir-server/src/main/resources/fhir/import.OperationDefinition.json
- fhir-server/src/main/resources/fhir/search.OperationDefinition.json
- pom.xml
- site/pom.xml
> Search request causes error when authorization is enabled

- encoders/core/pom.xml
- encoders/pom.xml
- encoders/r4/pom.xml
- fhir-server/pom.xml
- fhir-server/src/main/java/au/csiro/pathling/fhir/AnalyticsServer.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/AnalyticsServerCapabilities.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/AnalyticsServerConfiguration.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/AuthorisationInterceptor.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/OperationDefinitionProvider.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/SmartConfigurationInterceptor.java
- fhir-server/src/main/resources/fhir/aggregate.OperationDefinition.json
- fhir-server/src/main/resources/fhir/import.OperationDefinition.json
- fhir-server/src/main/resources/fhir/search.OperationDefinition.json
- pom.xml
- site/docs/getting-started.md
- site/pom.xml
> NullPointerException on request to /fhir with authorization enabled

- encoders/core/src/main/java/au/csiro/pathling/encoders/Bundles.java
- encoders/core/src/main/java/org/hl7/fhir/utilities/xhtml/XhtmlNode.java
- encoders/core/src/main/scala/au/csiro/pathling/encoders/EncoderBuilder.scala
- encoders/pom.xml
- encoders/r4/src/test/java/au/csiro/pathling/encoders/r4/BundlesTest.java
- fhir-server/src/main/java/au/csiro/pathling/FhirServerContainer.java
- fhir-server/src/main/java/au/csiro/pathling/fhir/AnalyticsServerCapabilities.java
- fhir-server/src/main/resources/fhir/aggregate.OperationDefinition.json
- fhir-server/src/main/resources/fhir/import.OperationDefinition.json
- fhir-server/src/main/resources/fhir/search.OperationDefinition.json
- fhir-server/src/test/java/au/csiro/pathling/DockerImageTest.java
- fhir-server/src/test/java/au/csiro/pathling/query/AggregateExecutorTest.java
- fhir-server/src/test/resources/responses/DockerImageTest-importDataAndQuery.Parameters.json
- pom.xml
- site/_sass/layout/_wrapper.scss
- site/docs/aggregate.md
- site/docs/import.md
- site/docs/search.md
- site/index.html
Fixes #3, #7, #21, #19 and #14.
> Upgrade Spark and HAPI

- fhir-server/src/main/java/au/csiro/pathling/query/AggregateProvider.java
> Check for null Parameters resource in aggregate operation

- fhir-server/src/main/java/au/csiro/pathling/query/parsing/LiteralComposer.java
- fhir-server/src/test/java/au/csiro/pathling/query/AggregateExecutorTest.java
- fhir-server/src/test/java/au/csiro/pathling/query/parsing/ExpressionParserTest.java
- fhir-server/src/test/resources/responses/AggregateExecutorTest-queryWithDateTimeGrouping.Parameters.json
> Fix problem with date time literals

- .github/workflows/deploy.yml
- .github/workflows/test.yml
> Enable integration tests within CI

- encoders/pom.xml
- encoders/pom.xml.releaseBackup
- fhir-server/.dockerignore
- fhir-server/Dockerfile
- fhir-server/pom.xml
- fhir-server/pom.xml.releaseBackup
- fhir-server/run.sh
- pom.xml
- pom.xml.releaseBackup
- release.properties
- site/docs/deployment.md
- site/pom.xml
- site/pom.xml.releaseBackup
> Add JAVA_OPTS environment variable, to allow configuration of the JVM

- fhir-server/src/main/java/au/csiro/pathling/aggregate/AggregateRequest.java
- fhir-server/src/main/java/au/csiro/pathling/aggregate/FreshAggregateExecutor.java
- fhir-server/src/main/resources/fhir/aggregate.OperationDefinition.json
- fhir-server/src/test/java/au/csiro/pathling/DockerImageTest.java
- fhir-server/src/test/java/au/csiro/pathling/aggregate/AggregateQueryTest.java
- fhir-server/src/test/java/au/csiro/pathling/aggregate/AggregateRequestBuilder.java
- fhir-server/src/test/java/au/csiro/pathling/aggregate/GroupingLiteralTest.java
> Remove labels from aggregate request

- fhir-server/src/main/java/au/csiro/pathling/Configuration.java
- fhir-server/src/main/java/au/csiro/pathling/errors/SecurityError.java
- fhir-server/src/main/java/au/csiro/pathling/io/AccessRules.java
- fhir-server/src/main/java/au/csiro/pathling/update/ImportExecutor.java
- fhir-server/src/main/resources/application.yml
- fhir-server/src/test/java/au/csiro/pathling/io/AccessRulesTest.java
> Added configuration of allowed URL sources for import.

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- fhir-server/src/test/java/au/csiro/pathling/aggregate/AggregateQueryTest.java
- fhir-server/src/test/java/au/csiro/pathling/fhirpath/parser/ParserTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/TimingExtension.java
- fhir-server/src/test/resources/logback-test.xml
- pom.xml
> Log out execution time for each AggregateExecutorTest and ParserTest

- fhir-server/src/main/java/au/csiro/pathling/fhir/ConformanceProvider.java
- fhir-server/src/test/resources/responses/CapabilityStatementTest/capabilityStatement.CapabilityStatement.json
> Fix operations against OperationDefinition in CapabilityStatement

- fhir-server/src/main/java/au/csiro/pathling/fhirpath/parser/Parser.java
- fhir-server/src/main/java/au/csiro/pathling/fhirpath/parser/ParserErrorListener.java
- fhir-server/src/test/java/au/csiro/pathling/fhirpath/parser/ParserTest.java
Added line and position in line in error message created in ParserErrorListener. Also, added an instance of this error listener to the lexer.
> Fixes #280.

- site/docs/configuration.md
> Updated documentation for server base to include X-Forwarded-Port

- fhir-server/src/main/java/au/csiro/pathling/update/ImportLock.java
> Add lock to prevent parallel import operations

- encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/R4DataTypeMappings.scala
- encoders/src/test/java/au/csiro/pathling/encoders/FhirEncodersTest.java
- encoders/src/test/java/au/csiro/pathling/encoders/SchemaConverterTest.java
- encoders/src/test/java/au/csiro/pathling/encoders/TestData.java
> Fix problem with encoding of answers within QuestionnaireResponse

- fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/ElementDefinition.java
- fhir-server/src/test/java/au/csiro/pathling/aggregate/AggregateQueryTest.java
- fhir-server/src/test/resources/responses/AggregateQueryTest/queryWithCanonicalGrouping.Parameters.json
> Add canonical and url to primitive type map

- fhir-server/src/main/java/au/csiro/pathling/fhirpath/ResourceDefinition.java
- fhir-server/src/main/java/au/csiro/pathling/search/CachingSearchProvider.java
- fhir-server/src/main/java/au/csiro/pathling/search/SearchProvider.java
> Fix lookup of List resource using class passed from HAPI operation

- fhir-server/src/main/java/au/csiro/pathling/QueryExecutor.java
- fhir-server/src/main/java/au/csiro/pathling/aggregate/AggregateExecutor.java
> Optimising joins between filters and groupings.

- encoders/src/main/scala/au/csiro/pathling/encoders/DeserializerBuilder.scala
- encoders/src/main/scala/au/csiro/pathling/encoders/SchemaProcessor.scala
- encoders/src/main/scala/au/csiro/pathling/encoders/SchemaProcessorWithTypeMappings.scala
- encoders/src/test/java/au/csiro/pathling/encoders/FhirEncodersTest.java
- encoders/src/test/java/au/csiro/pathling/encoders/SchemaConverterTest.java
> Resolve outstanding TODO items in encoders v2.

- .github/workflows/test.yml
- fhir-server/pom.xml
- fhir-server/src/test/java/au/csiro/pathling/aggregate/AggregateQueryTest.java
- fhir-server/src/test/java/au/csiro/pathling/extract/ExtractQueryTest.java
- fhir-server/src/test/java/au/csiro/pathling/security/ga4gh/ManifestConverterTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/AsyncSecurityTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/AsyncTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/AuthorizationConfigurationTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/CachedSearchTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/CapabilityStatementTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/ExtractSecurityTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/ExtractTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/MultipleAggregationsAndResolveTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/SearchTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/SentryTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/TerminologyServiceIntegrationTest.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/modification/ModificationTest.java
The tests are starting to take longer and longer to execute (~30 mins). This change splits the tests into three separate tranches (hopefully of roughly equal execution time) and sets them up to run in parallel.
> Split test suite into tranches

- fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/ReferencePath.java
- fhir-server/src/test/java/au/csiro/pathling/fhirpath/parser/ParserTest.java
> Return correct error when accessing unsupported Reference children

- fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/DateTimeLiteralPath.java
- fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/LiteralPath.java
- fhir-server/src/test/java/au/csiro/pathling/aggregate/DrillDownBuilderTest.java
- pom.xml
> Fix gaps in translation of results into literals within drill-down

- fhir-server/src/main/java/au/csiro/pathling/security/SecurityConfiguration.java
> Replace WebSecurityConfigurerAdapter with SecurityFilterChain bean

- fhir-server/src/main/java/au/csiro/pathling/io/Database.java
- fhir-server/src/test/resources/requests/BatchTest/batch.Bundle.json
> Fix error relating to use of URN in fullUrl in batch

- lib/import/README.md
- lib/import/azure-pipelines.yml
- lib/import/package-lock.json
- lib/import/package.json
- lib/import/src/checkStatus.ts
- lib/import/src/common.ts
- lib/import/src/config.ts
- lib/import/src/export.ts
- lib/import/src/handlers.ts
- lib/import/src/import.ts
- lib/import/src/index.ts
- lib/import/src/sentry.ts
- lib/import/src/transferToS3.ts
Changes to the import library to remove the requirement for authentication at both ends, and also to make it possible to change the import mode.
Resolves #781.
> Enable use of unauthenticated source and target

- lib/import/package-lock.json
- lib/import/package.json
- lib/js/package-lock.json
- lib/js/package.json
https://github.com/axios/axios/issues/5011
> Move axios back to ^0.27.2

- encoders/pom.xml
- fhir-server/pom.xml
- fhir-server/src/main/java/au/csiro/pathling/sql/dates/TemporalArithmeticFunction.java
- fhir-server/src/main/java/au/csiro/pathling/sql/dates/TemporalComparisonFunction.java
- fhir-server/src/main/java/au/csiro/pathling/sql/dates/date/DateArithmeticFunction.java
- fhir-server/src/main/java/au/csiro/pathling/sql/dates/datetime/DateTimeArithmeticFunction.java
- fhir-server/src/main/java/au/csiro/pathling/sql/dates/datetime/DateTimeComparisonFunction.java
- fhir-server/src/main/java/au/csiro/pathling/sql/dates/time/TimeComparisonFunction.java
- fhir-server/src/test/java/au/csiro/pathling/fhirpath/operator/ComparisonOperatorInstantTest.java
- fhir-server/src/test/java/au/csiro/pathling/fhirpath/operator/DateArithmeticTest.java
- lib/import/pom.xml
- lib/js/pom.xml
- lib/python/pom.xml
- library-api/pom.xml
- pom.xml
- site/docs/fhirpath/operators.md
- site/pom.xml
- terminology/pom.xml
- utilities/pom.xml
> Fix comparison and arithmetic operations for instants

- encoders/pom.xml
- fhir-server/pom.xml
- fhir-server/src/main/java/au/csiro/pathling/async/AsyncAspect.java
- fhir-server/src/main/java/au/csiro/pathling/errors/ErrorReportingInterceptor.java
- lib/import/pom.xml
- lib/js/pom.xml
- lib/python/pom.xml
- library-api/pom.xml
- pom.xml
- site/pom.xml
- terminology/pom.xml
- utilities/pom.xml
Resolves #1003.
Resolves #1028.
> Apply the same exception reporting rules for async requests as the synchronous ones.

- fhir-server/src/main/java/au/csiro/pathling/fhirpath/function/terminology/TranslateFunction.java
- fhir-server/src/test/java/au/csiro/pathling/sql/udf/TerminologyUdsfTest.java
- lib/python/pathling/udfs.py
- lib/python/tests/test_udfs.py
- terminology/src/main/java/au/csiro/pathling/sql/Terminology.java
- terminology/src/main/java/au/csiro/pathling/sql/TerminologySupport.java
- terminology/src/main/java/au/csiro/pathling/sql/udf/TerminologyUdfHelpers.java
- terminology/src/main/java/au/csiro/pathling/sql/udf/TranslateUdf.java
- terminology/src/main/java/au/csiro/pathling/terminology/DefaultTerminologyService2.java
- terminology/src/main/java/au/csiro/pathling/terminology/TerminologyFunctions.java
- terminology/src/test/java/au/csiro/pathling/sql/TerminologySupportTest.java
- terminology/src/test/java/au/csiro/pathling/sql/udf/TranslateOfUdfTest.java
- terminology/src/test/java/au/csiro/pathling/terminology/DefaultTerminologyService2Test.java
> Optimisations of translate() and subsumes() UDFs.

- library-api/src/main/java/au/csiro/pathling/library/PathlingContext.java
- library-api/src/test/java/au/csiro/pathling/library/PathlingContextTest.java
- pom.xml
- terminology/src/main/java/au/csiro/pathling/config/HttpClientCachingConfiguration.java
- terminology/src/main/java/au/csiro/pathling/config/TerminologyConfiguration.java
- utilities/pom.xml
- utilities/src/main/java/au/csiro/pathling/validation/ValidationUtils.java
Implements validation of encoders and terminology configuration for PahtlingContext.
.
> Implements validation of configuration for PahtlingContext.

- lib/python/local.Dockerfile
- lib/python/pathling/context.py
- library-api/src/main/java/au/csiro/pathling/library/PathlingContext.java
- site/docs/libraries/databricks.md
- site/docs/libraries/spark-cluster.md
> Ensure that Pathling git.properties takes precedence over Spark environment

- pom.xml
- utilities/pom.xml
- utilities/src/main/java/au/csiro/pathling/validation/ValidationUtils.java
> Removing JSR-380 validation dependency on EL implementation.

- terminology/src/main/java/au/csiro/pathling/terminology/DefaultTerminologyServiceFactory.java
> Add IdleConnectionEvictor to guard against terminology server closing connections

- fhir-server/src/test/java/au/csiro/pathling/extract/ExtractQueryTest.java
- fhir-server/src/test/resources/responses/ExtractQueryTest/resolveAndCodingLiteralColumn.csv
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPath.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/literal/LiteralPath.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/operator/CombineOperator.java
> Implemented aliasing of the literal value columns.

- fhirpath/src/test/java/au/csiro/pathling/views/AbstractFhirViewTestBase.java
- fhirpath/src/test/java/au/csiro/pathling/views/FhirViewComplianceTest.java
- fhirpath/src/test/java/au/csiro/pathling/views/JsonReportingExtension.java
> Produce and publish SQL on FHIR test reports

- deployment/helm/pom.xml
- encoders/pom.xml
- fhir-server/pom.xml
- fhir-server/src/main/java/au/csiro/pathling/security/SecurityConfiguration.java
- fhir-server/src/test/java/au/csiro/pathling/test/integration/CapabilityStatementTest.java
- fhirpath/pom.xml
- lib/R/pom.xml
- lib/import/pom.xml
- lib/js/pom.xml
- lib/python/Dockerfile
- lib/python/pom.xml
- library-api/pom.xml
- library-runtime/pom.xml
- pom.xml
- site/docs/libraries/installation/spark.md
- site/pom.xml
- terminology/pom.xml
- utilities/pom.xml
> Fix issue with CORS not working when authentication is disabled

- fhirpath/src/main/java/au/csiro/pathling/fhirpath/CalendarDurationUtils.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/EvaluationContext.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPathDurationUnit.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/LegacyEvaluationContext.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DecimalCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/context/ResourceResolver.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/context/ViewEvaluationContext.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/execution/BaseResourceResolver.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/execution/DefResourceResolver.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/parser/InvocationVisitor.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/path/Paths.java
- fhirpath/src/main/java/au/csiro/pathling/sql/dates/TemporalArithmeticFunction.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/literal/StringLiteralPathTest.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/yaml/YamlFhirpathTest.java
- fhirpath/src/test/java/au/csiro/pathling/test/yaml/TestConfig.java
- fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSpecTestBase.java
- fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlTest.java
- fhirpath/src/test/resources/fhirpath-js/config.yaml
- fhirpath/src/test/resources/fhirpath-ptl/cases/literals.yaml
- fhirpath/src/test/resources/fhirpath-ptl/cases/quantities.yaml
- utilities/src/main/java/au/csiro/pathling/fhirpath/literal/StringLiteral.java
Resolves #2146 , #2165, #2145, #2169
> Small bug fixes for reference.js issues

- .github/workflows/test.yml
- encoders/src/main/java/au/csiro/pathling/sql/types/FlexiDecimal.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/Numeric.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DateCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DateTimeCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DecimalCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/IntegerCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/QuantityCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/ColumnRepresentation.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/encoding/QuantityEncoding.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/operator/PolarityOperator.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/operator/UnaryOperator.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/parser/Visitor.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/path/Paths.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/yaml/YamlFhirpathTest.java
- fhirpath/src/test/resources/fhirpath-js/config.yaml
- fhirpath/src/test/resources/fhirpath-ptl/cases/math.yaml
- lib/R/pom.xml
- pom.xml
> Implementation of the polarity (+/-) operator

- .gitignore
- fhir-server/src/test/java/au/csiro/pathling/extract/ExtractQueryTest.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/StringCoercible.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/BooleanCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/CodingCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DateCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DecimalCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/EmptyCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/IntegerCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/QuantityCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/StringCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/ColumnRepresentation.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/DecimalRepresentation.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/DefaultRepresentation.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/encoding/QuantityEncoding.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/provider/ConversionFunctions.java
- fhirpath/src/main/java/au/csiro/pathling/sql/misc/DecimalToLiteral.java
- fhirpath/src/main/java/au/csiro/pathling/sql/misc/MiscUDFRegistrar.java
- fhirpath/src/main/java/au/csiro/pathling/sql/misc/QuantityToLiteral.java
- fhirpath/src/main/java/au/csiro/pathling/sql/misc/ToNull.java
- fhirpath/src/main/java/au/csiro/pathling/view/Projection.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/yaml/YamlFhirpathTest.java
- fhirpath/src/test/java/au/csiro/pathling/sql/misc/DecimalToLiteralTest.java
- fhirpath/src/test/java/au/csiro/pathling/sql/misc/QuantityToLiteralTest.java
- fhirpath/src/test/resources/fhirpath-js/config.yaml
- fhirpath/src/test/resources/fhirpath-ptl/cases/conversion_functions.yaml
> Complete toString() implementation.

- fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPathType.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/ColumnRepresentation.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/operator/CollectionOperations.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/yaml/YamlFhirpathTest.java
- fhirpath/src/test/java/au/csiro/pathling/test/yaml/FhipathTestSpec.java
- fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSpecTestBase.java
- fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSupport.java
- fhirpath/src/test/resources/fhirpath-js/config.yaml
- fhirpath/src/test/resources/fhirpath-ptl/cases/operators.yaml
- fhirpath/src/test/resources/fhirpath-ptl/resources/Encounter_with_participants.json
- fhirpath/src/test/resources/fhirpath-ptl/resources/Observation_1.json
- fhirpath/src/test/resources/fhirpath-ptl/resources/Observation_3_comp.json
> Review membership operators and implement correct behaviour for empty elements.

- .github/workflows/test.yml
> Pre-install spark distribution for CI sparkly from our mirror.

- encoders/src/main/scala/au/csiro/pathling/encoders/Expressions.scala
- encoders/src/main/scala/au/csiro/pathling/encoders/SerializerBuilder.scala
- encoders/src/test/java/au/csiro/pathling/encoders/FhirEncodersTest.java
- library-api/src/test/java/au/csiro/pathling/library/io/DataSourcesTest.java
> FIxing traversal to choice fields for JSON datasource.

- fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/provider/StringFunctions.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/registry/StaticFunctionRegistry.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/StringFunctionsDslTest.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/execution/SingleResourceFhirpathTest.java
> Implement join() function.

- fhirpath/src/main/java/au/csiro/pathling/view/Projection.java
- fhirpath/src/test/resources/viewTests/misc.json
> Fixing the issue with rendering of empty columns in fhir view.

- fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPathType.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/mixed/ChoiceElementCollection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/ColumnRepresentation.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/FilteringAndProjectionFunctionsDslTest.java
> Implement 'ofType()' for fhirpath (System) types in polymorphic collections.

- fhirpath/src/test/resources/viewTests/misc.json
- lib/python/requirements/package.txt
- lib/python/setup.py
- lib/python/tests/test_view.py
> Updating required spark version to 3.5.2

- fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/CollectionTransform.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/provider/FilteringAndProjectionFunctions.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/parser/Visitor.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/ExistenceFunctionsDslTest.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/SystemDslTest.java
- fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSupport.java
- fhirpath/src/test/resources/fhirpath-js/config.yaml
> Minor fixes to the boolean collection evaluation

- fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/definition/ElementDefinition.java
- fhirpath/src/main/java/au/csiro/pathling/fhirpath/definition/fhir/FhirElementDefinition.java
- fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/SystemDslTest.java
> Log a warning when using type suffix on choice paths

- .github/workflows/release.yml
- site/docs/libraries/examples/sql-on-fhir-examples.md
This change adds a job to the release workflow to automatically upload the source code to the Pathling collection on data.csiro.au.
> Add upload to CSIRO Data Access Portal
